tasks: $tasks
init:
  sourcePath: $Pwd(..)
  buildPath: /tmp/dbsync
  Version: $Cat(../Version)

defaults:
  target: $target
pipeline:

  stop:
    transfer:
      action: process:stop-all
      input: vtransfer
    sync:
      action: process:stop-all
      input: vsync

  setSdk:
    action: sdk:set
    sdk: $sdk

  cleanup:
    action: exec:run
    systemPaths:
      - /usr/local/bin
    commands:
      - rm $sourcePath/transfer/app/vtransfer
      - rm $sourcePath/transfer/app/nohup.out
      - rm $sourcePath/sync/app/nohup.out
      - rm $sourcePath/sync/app/vsync
      - rm -rf $sourcePath/sync/app/cron


  build:
    action: exec:run
    systemPaths:
      - /usr/local/bin
    checkError: true
    commands:
      - export GO111MODULE=on
      - unset GOPATH
      - export LD_LIBRARY_PATH=${env.LD_LIBRARY_PATH}
      - export PKG_CONFIG_PATH=${env.LD_LIBRARY_PATH}
      - cd $sourcePath/transfer/app
      - go build -ldflags "-X main.Version=${Version}-e2e" -o vtransfer
      - cd $sourcePath/sync/app
      - go build -ldflags "-X main.Version=${Version}-e2e" -o vsync


  start:
    transfer:
      action: process:start
      directory: $sourcePath/transfer/app
      immuneToHangups: true
      command: ./vtransfer -debug=true
    sync:
      action: process:start
      directory: $sourcePath/sync/app
      immuneToHangups: true
      command: ./vsync -port=8081

