init:
  app: dstransfer
  sdk: go:1.12
  target:
    URL: ssh://127.0.0.1/
    credentials: localhost
  bqCredentials: gcp-e2e
  mysqlCredentials: mysql-e2e
  pgCredentials: pg-e2e
  oraCredentials: ora-e2e
  oraAdminCredentials: ora-admin-e2e
  useDockerDBIP: true
  dbIP:
    ora: 127.0.0.1
    pg: 127.0.0.1
    mysql: 127.0.0.1
    aero: 127.0.0.1

pipeline:
  init:
    system:
      action: run
      request: '@system'
      tasks: '*'

    fetchDbIp:
      when: $useDockerDBIP = true
      action: run
      request: '@dbip.yaml'

    info:
      action: print
      message: 'Db IP: $AsJSON($dbIP)'

    datastore:
      action: run
      request: '@datastore'
      tasks: '*'

    app:
      sdk: $sdk
      action: run
      request: '@app'
      tasks: '*'
  test:
    action: run
    request: '@regression/regression'
    tasks: '*'
  destroy:
    app:
      buildTarget: $target
      app: $app
      appVersion: $appVersion
      action: run
      request: '@app'
      tasks: stop
    system:
      action: run
      request: '@system'
      tasks: destroy
