version: "3.2"
services:
  dbtransfer:
    container_name: dbtransfer
    image: us.gcr.io/tech-ops-poc/vdbtransfer:0.1
    command: ["./dbtransfer"]
    ports:
      - 8080:8080
    volumes:
      - ${HOME}/.secret/:/root/.secret/
    network_mode: bridge
