pipeline:
  db1:
   register:
      action: dsunit:register
      datastore: db1
      config:
        driverName: mysql
        descriptor: '[username]:[password]@tcp(127.0.0.1:3306)/[dbname]?parseTime=true'
        credentials: $mysqlCredentials

  db2:
    register:
      action: dsunit:register
      datastore: db2
      config:
        driverName: mysql
        descriptor: '[username]:[password]@tcp(127.0.0.1:3306)/[dbname]?parseTime=true'
        credentials: $mysqlCredentials

  mysql-ip:
    action: docker:inspect
    logging: false
    name: dbsync
    post:
      - dbIP = $Info[0].NetworkSettings.IPAddress
      - mysqlIP = $Info[0].NetworkSettings.IPAddress
